const projects = {
  'smart-hub': { name: 'Smart Power Hub', year: '2026', title: 'A safer, smarter<br><em>extension board.</em>', summary: 'An ESP32-enabled Smart Power Hub that began as my personal concept, then became a CAD group project and practical prototype with my team.', image: '../assets/smart-hub.jpg', heading: 'Control power — and protect it.', description: 'I proposed this project when our CAD group needed a direction, then we developed it together from concept to working prototype. The extension board uses an ESP32 microcontroller with smoke, water/moisture, and temperature sensors. A Wi-Fi UI server lets a user connect by phone, enter the board’s IP address in a browser, switch the extension board on or off, and schedule its operating time. When the system detects smoke, a leak, or high temperature, the buzzer sounds, an alert is sent to the phone, and the board can lock or switch off until the condition is resolved.', scope: 'Concept lead, CAD modelling, ESP32 integration, safety-sensor and Wi-Fi UI design', outcome: 'A working prototype concept for remote control, scheduling, alerts, and automatic safety shut-off', quote: '“A practical device should be simple to understand — and safe enough to trust.”', credit: '— Project principle', next: 'robotics' },
  robotics: { name: 'Robotics Prototype', year: '2025', title: 'Learning through<br><em>movement.</em>', summary: 'A hands-on robotics project focused on testing physical systems, observing behaviour, and improving an idea through direct experimentation.', image: '../assets/robotics.jpg', heading: 'Build, test, refine.', description: 'Working with a physical robotics prototype made the design process tangible. It brought together mechanical reasoning, careful observation, and the willingness to adjust a solution after seeing how it performs in the real world.', scope: 'Prototype work, mechanical systems, testing', outcome: 'Practical experience connecting engineering concepts to working hardware', quote: '“The best feedback often comes from seeing a prototype move.”', credit: '— Project reflection', next: 'mechanical' },
  mechanical: { name: 'Mechanical Assembly', year: '2026', title: 'Parts made to<br><em>come together.</em>', summary: 'A detailed CAD assembly study exploring the relationship between individual components, fastening, motion, and manufacturable form.', image: '../assets/mechanical-assembly.png', heading: 'Making the assembly readable.', description: 'This Fusion 360 assembly was developed as an exercise in mechanical construction and visual communication. Each part was modelled to show how components meet, how fasteners hold the structure together, and how the object can be understood as a whole.', scope: 'Fusion 360, component modelling, assembly design', outcome: 'A precise 3D assembly model with clear component relationships', quote: '“Good assemblies are resolved one connection at a time.”', credit: '— Design principle', next: 'circuit' },
  circuit: { name: 'Combined Circuit Study', year: '2025', title: 'Signals made<br><em>visible.</em>', summary: 'A final-semester group build based on assigned laboratory work, bringing multiple circuit stages into one clear alarm system.', image: '../assets/circuit.jpg', heading: 'Leading the build from schematic to circuit.', description: 'For our final-semester group project, we were given laboratory work from a course book and asked to build it. I led the group and created the circuit schematics, coordinating how the Wheatstone bridge, difference amplifier, comparator, and LED alarm work together. The related circuit studies in the archive also include my individual classwork and assignments, showing the practical stages behind the larger group build.', scope: 'Group leadership, circuit schematic design, electronics laboratory work', outcome: 'A documented build that traces sensor input through amplification, comparison, and alarm output', quote: '“Complex systems become manageable when each stage has a clear job.”', credit: '— Project reflection', next: 'smart-hub' }
};
const project = projects[new URLSearchParams(location.search).get('project')] || projects['smart-hub'];
document.title = `${project.name} — Iqram Abubakar`;
document.querySelector('#project-kicker').textContent = `${project.name} · ${project.year}`;
document.querySelector('#project-title').innerHTML = project.title;
document.querySelector('#project-summary').textContent = project.summary;
document.querySelector('#project-visual').className = 'case-hero image-case';
document.querySelector('#project-visual').innerHTML = `<img src="${project.image}" alt="${project.name}" style="width:100%;height:100%;object-fit:cover;display:block">`;
['heading', 'description', 'scope', 'outcome', 'quote', 'credit'].forEach((key) => { document.querySelector(`#project-${key}`).textContent = project[key]; });
const next = projects[project.next];
const nextLink = document.querySelector('#next-project');
nextLink.href = `?project=${project.next}`;
nextLink.textContent = `Next project: ${next.name} →`;
