const projects = {
  'smart-hub': { name: 'Smart Power Hub', year: '2026', title: 'A safer, smarter<br><em>extension board.</em>', summary: 'This project grew from a simple problem: a standard extension board was useful, but not intelligent or safe enough for more demanding everyday use. I developed the concept into a CAD-led prototype with remote control, monitoring, and protective sensing.', image: '../assets/smart-hub.jpg', heading: 'Control power — and protect it.', description: 'The main need behind this project was to make an ordinary power extension system safer and easier to manage. Instead of treating it as a passive device, I approached it as a connected control system: define the use case, model the concept in CAD, test the layout, and then build a prototype around the real operating risks. The design uses an ESP32 board, sensors for smoke, moisture, and temperature, and a browser-based interface so a user can switch the board on or off, schedule operation, and monitor the system remotely. The result was a practical prototype that added safety logic, alarm feedback, and more deliberate control without making the system difficult to understand.', scope: 'Concept lead, CAD modelling, ESP32 integration, safety-sensor and Wi-Fi UI design', outcome: 'A working prototype concept for remote control, scheduling, alerts, and automatic safety shut-off', quote: '“A practical device should be simple to understand — and safe enough to trust.”', credit: '— Project principle', next: 'robotics' },
  robotics: { name: 'Robotics Prototype', year: '2025', title: 'Learning through<br><em>movement.</em>', summary: 'This project was less about building a final product and more about learning through movement: testing a concept physically, observing how it behaved, and refining the design based on what the prototype actually did.', image: '../assets/robotics.jpg', heading: 'Build, test, refine.', description: 'The challenge here was not only to design a robotic concept, but to understand how that concept behaved in the real world. I approached the work as a hands-on testing exercise: build the mechanism, observe how it moves, note where the motion or stability breaks down, and refine the design based on what the prototype reveals. That process helped connect mechanical reasoning with practical testing, making the design decisions more grounded in real behaviour rather than assumptions. The work reinforced the idea that engineering improves when a concept is allowed to move, fail, and be corrected in physical form.', scope: 'Prototype work, mechanical systems, testing', outcome: 'Practical experience connecting engineering concepts to working hardware', quote: '“The best feedback often comes from seeing a prototype move.”', credit: '— Project reflection', next: 'mechanical' },
  mechanical: { name: 'Mechanical Assembly', year: '2026', title: 'Parts made to<br><em>come together.</em>', summary: 'This assembly study focused on understanding how individual parts interact within a full mechanical system, with attention to fit, motion, fastening, and manufacturability.', image: '../assets/mechanical-assembly.png', heading: 'Making the assembly readable.', description: 'The main challenge in this project was seeing beyond the individual component and understanding how a complete mechanical idea comes together. I approached the design by modelling each part deliberately, examining how it connects to the next, and making sure the assembly communicates its function clearly. The process involved thinking about fasteners, alignment, feature placement, motion, and how the final object could be understood visually as a coherent mechanism. The outcome was a clearer CAD assembly that shows not only the part itself, but how the part behaves as part of a larger system.', scope: 'Fusion 360, component modelling, assembly design', outcome: 'A precise 3D assembly model with clear component relationships', quote: '“Good assemblies are resolved one connection at a time.”', credit: '— Design principle', next: 'circuit' },
  circuit: { name: 'Combined Circuit Study', year: '2025', title: 'Signals made<br><em>visible.</em>', summary: 'This final-semester circuit study brought several lab stages together into one system, translating classroom theory into a working alarm arrangement with clear signal flow and documentation.', image: '../assets/circuit.jpg', heading: 'Leading the build from schematic to circuit.', description: 'The project began with the need to combine several circuit stages into a single, understandable alarm system. As the group leader, I helped coordinate the build by developing the circuit logic, mapping how each stage connected to the next, and making sure the system remained clear as it moved from input through amplification and comparison to a visible output. The work relied on the laboratory sequence itself: tracing how a signal changes as it passes through each stage, then documenting the final arrangement so the logic remained simple to follow. The result was a clearly structured build that turned a set of separate circuit exercises into one functioning system.', scope: 'Group leadership, circuit schematic design, electronics laboratory work', outcome: 'A documented build that traces sensor input through amplification, comparison, and alarm output', quote: '“Complex systems become manageable when each stage has a clear job.”', credit: '— Project reflection', next: 'smart-hub' }
};
const project = projects[new URLSearchParams(location.search).get('project')] || projects['smart-hub'];
document.title = `${project.name} — Iqram Abubakar`;
document.querySelector('#project-kicker').textContent = `${project.name} · ${project.year}`;
document.querySelector('#project-title').innerHTML = project.title;
document.querySelector('#project-summary').textContent = project.summary;
document.querySelector('#project-visual').className = 'case-hero image-case';
document.querySelector('#project-visual').innerHTML = `<img src="${project.image}" alt="${project.name}" style="width:100%;height:100%;object-fit:cover;display:block">`;
['heading', 'description', 'scope', 'outcome', 'quote', 'credit'].forEach((key) => { document.querySelector(`#project-${key}`).textContent = project[key]; });
const next = projects[project.next];
const nextLink = document.querySelector('#next-project');
nextLink.href = `?project=${project.next}`;
nextLink.textContent = `Next project: ${next.name} →`;
